#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_DP)                   += dp/
obj-$(CONFIG_NUBIA_SENSORS_SENS)         += sensors_sensitivity/
obj-$(CONFIG_NUBIA_BYPASS_ACL)                    += bypass_acl/
