obj-m += zte_goodix_core.o

zte_goodix_core-objs := goodix_brl_i2c.o goodix_ts_core.o goodix_brl_hw.o goodix_cfg_bin.o goodix_ts_utils.o goodix_brl_fwupdate.o goodix_ts_tools.o goodix_ts_gesture.o goodix_common_interface.o goodix_ts_inspect.o tpd_sys.o tpd_ufp_mac.o zte_edge_suppression.o

BOARD_VENDOR_KERNEL_MODULES +=  $(KERNEL_MODULES_OUT)/zte_goodix_core.ko
